### PR TITLE
Use default text editor and gtk4

### PR DESCRIPTION
**Pull request by 103sbavert**
Remove the hard coded path of the gedit and use the text editor to make it more convenient for those that use a third party text editor or gnome's new text editor named "Gnome Text Editor".

### CODE REVIEW

**Comment by CorvetteCole** [comment]
it would be great to also support different terminals in case someone is using gnome-console or blackbox and doesn't have gnome-terminal installed

**Comment by sbeve72** [comment]
Are you asking to add a new feature that shows `Open in <terminal>`? Because as far as I know, this extension doesn't have any such feature yet. But just in case you're asking to add that as a feature, I will let you know that there's exists another Nautilus extension https://github.com/Stunkymonkey/nautilus-open-any-terminal.

**Comment by CorvetteCole** [comment]
Oh I'm sorry, that was an enormous brain blank. Nautilus already natively supports this. I don't know what I mean... I'll leave these here, but ignore me!

**Comment by MacTavishAO** [comment]
Looks good to me apart from hardcoded nautilus path. Could you elaborate on that?

**Comment by 103sbavert** [comment]
At the time I wrote this code, I didn't know anything ab GTK or the API and I was new to Gnome and was missing this feature from KDE. I think if you could suggest some changes, I will make them so as to replace the hardcoded nautilus path. Other than that, I don't know how one would get the path for the system nautilus installation.

**Comment by MacTavishAO** [comment]
> At the time I wrote this code, I didn't know anything ab GTK or the API and I was new to Gnome and was missing this feature from KDE. I think if you could suggest some changes, I will make them so as to replace the hardcoded nautilus path. Other than that, I don't know how one would get the path for the system nautilus installation.

That'd be great. That change could break distros that haven't moved to usr, if there are any and, BSDs that install packages to /usr/local/

**Comment by MacTavishAO** [comment]
Thank you!

**Pull request merged**
